# Generated by Django 3.2.4 on 2021-06-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BID', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('License', models.CharField(max_length=14)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Portfolio_ID', models.CharField(max_length=15)),
                ('PAN', models.CharField(max_length=14)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Company', models.CharField(max_length=50)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shares', models.FloatField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.broker')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
