# Generated by Django 3.2.4 on 2021-06-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_broker',
            old_name='PID',
            new_name='CID',
        ),
    ]
